### ISSUE TITLE
colorbar or legend not work for Graph

### ISSUE THREAD

**Issue by kwunlyou** [pyviz/holoviews#4069] opened 2019-10-23 09:38 UTC
```python
import pandas as pd
import holoviews as hv
#hv.extension('bokeh')
hv.notebook_extension('bokeh')

## Declaring data

edges_df = pd.read_csv('fb_edges.csv')
nodes_df = pd.read_csv('fb_nodes.csv')

fb_nodes = hv.Nodes(nodes_df).sort()
fb_graph = hv.Graph((edges_df, fb_nodes), label='Facebook Circles')

## Plot

colors = ['#000000']+hv.Cycle('Category20').values
fb_graph = fb_graph.redim.range(x=(-0.05, 1.05), 
                                y=(-0.05, 1.05)
                               )
```

```python
# not work
fb_graph.opts(color_index='circle', width=800, height=800, show_frame=False,
                 xaxis=None, yaxis=None,node_size=10, edge_line_width=1, cmap=colors, colorbar=True)

# not work as well
fb_graph.opts(color_index='circle', width=800, height=800, show_frame=False,
                 xaxis=None, yaxis=None,node_size=10, edge_line_width=1, cmap=colors, show_legend=True)
```

**Comment by philippjfr** [comment] 2019-10-23 13:55
Thanks for the report, this is a duplicate of #3509

**Closed by philippjfr** 2019-10-23 13:55 UTC
