### ISSUE TITLE
Add slopes annotation

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoviews#4001] opened 2019-09-27 04:24 UTC
Bokeh has implemented slope annotations
https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html

**Comment by philippjfr** [comment] 2019-09-27 10:50
Already started on this: https://github.com/pyviz/holoviews/issues/4001

**Comment by philippjfr** [comment] 2019-10-01 19:23
Also a duplicate of #1993 and #2988. Closing.

**Closed by philippjfr** 2019-10-01 19:23 UTC
