### ISSUE TITLE
Datashade operations should not apply to unsupported elements

### ISSUE THREAD

**Issue by suyang-nju** [pyviz/holoviews#2692] opened 2018-05-17 15:16 UTC
Something like `dynspread(datashade(gridmatrix(...)))` would be nice. Elements that can't be datashaded (e.g., diagonal histograms or distributions) are ignored and kept as is.

**Comment by philippjfr** [comment] 2018-05-17 16:57
I agree that datashade should not apply to elements that do not really support it (e.g. Histogram), however for the time being you could do something like this:

```python
from holoviews.operation import gridmatrix
from holoviews.operation.datashader import datashade, dynspread
some_dataset = hv.Table(np.random.rand(1000, 5), [chr(65+i)+'_dimension' for i in range(5)])

gridmatrix(some_dataset).map(datashade, hv.Scatter).map(dynspread, hv.RGB)
```

**Comment by suyang-nju** [comment] 2018-05-17 18:33
Thanks!

**Comment by suyang-nju** [comment] 2018-05-18 22:33
When use this method with a HoloMap data

    some_dataset = hv.HoloMap({key: hv.Dataset(np.random.rand(1000, 5), [chr(65+i)+'_dimension' for i in range(5)]) 
                               for key in ['one', 'two', 'three']})
    gridmatrix(some_dataset).map(datashade, hv.Scatter).map(dynspread, hv.RGB)

I got

    ~/anaconda/lib/python3.6/site-packages/holoviews/plotting/util.py in collate(obj)
         85             raise Exception(undisplayable_info(obj))
         86     else:
    ---> 87         raise Exception(undisplayable_info(obj))
         88 
         89 

    Exception: GridSpace containing HoloMaps of Layouts cannot be displayed.
    Please call the collate method on the appropriate elements.
    For more information, please consult the Composing Data tutorial (http://git.io/vtIQh)

    :GridMatrix   [X,Y]
       :HoloMap   [Default]
          :Histogram   [E_dimension]   (E_dimension_frequency)

What are the appropriate elements to call collate on? 

If instead to make a HoloMap of gridmatrices:

    some_dataset = {key: hv.Dataset(np.random.rand(1000, 5), [chr(65+i)+'_dimension' for i in range(5)])
                    for key in ['one', 'two', 'three']}
    hv.HoloMap({k: gridmatrix(some_dataset[k]).map(hd.datashade, hv.Scatter).map(hd.dynspread, hv.RGB) 
                for k in some_dataset})

then

    ~/anaconda/lib/python3.6/site-packages/holoviews/plotting/bokeh/plot.py in __init__(self, layout, ranges, layout_num, keys, **params)
        448     def __init__(self, layout, ranges=None, layout_num=1, keys=None, **params):
        449         if not isinstance(layout, GridSpace):
    --> 450             raise Exception("GridPlot only accepts GridSpace.")
        451         super(GridPlot, self).__init__(layout=layout, layout_num=layout_num,
        452                                        ranges=ranges, keys=keys, **params)

    Exception: GridPlot only accepts GridSpace.

    :HoloMap   [Default]
       :GridMatrix   [X,Y]
          :Histogram   [E_dimension]   (E_dimension_frequency)

**Comment by philippjfr** [comment] 2018-05-18 22:37
That's bizarre and should not happen, this is perfectly valid:

```
:GridMatrix   [X,Y]
   :HoloMap   [Default]
      :Histogram   [E_dimension]   (E_dimension_frequency)
```

Will have to try to reproduce.

**Comment by suyang-nju** [comment] 2018-05-20 05:44
Looks like `gridmatrix(some_dataset)` alone works fine with a HoloMap `some_dataset`. The issue appears only when trying to datashade with `.map(datashade, hv.Scatter).map(dynspread, hv.RGB)`

**Comment by philippjfr** [comment] 2019-10-03 01:02
The real issue here is that datashade/rasterize should not apply to elements they don't understand, e.g. a Histogram.

**Comment by jbednar** [comment] 2019-10-03 12:17
Sounds correct to me; most of the time when datashading isn't supported for an Element it's because it's not a particularly meaningful thing to do, so silently skipping datashading for those Elements seems appropriate.  We might want to warn in the case of datashading/rasterizing a single unsupported Element type, which is a trickier call; in explicit interactive use such a warning is probably helpful feedback to the user, but in a pipeline where people just want to make sure no big data ever makes it through to the browser they should be free to datashade/rasterize whatever they are given and have it silently skip unsupported things.  On balance I _think_ I come down on the side of not warning for such cases, but I'm not committed to that.

**Comment by philippjfr** [comment] 2019-10-03 12:20
>in a pipeline where people just want to make sure no big data ever makes it through to the browser they should be free to datashade/rasterize whatever they are given and have it silently skip unsupported things

Right, particularly for composite objects like this one it'd be preferable to be silent.

>On balance I think I come down on the side of not warning even when provided a single unsupported Element, but I'm not committed to that.

Don't have a strong feeling here but was leaning towards warning here, sadly detecting that case is somewhat cumbersome so it'd certainly be simpler.

**Comment by jbednar** [comment] 2019-10-03 14:10
I'll leave that up to you, then; a warning would be fine, assuming it can be silenced by always wrapping everything in a Layout, but I can't say whether it's worth the effort.

**Closed** 2019-10-03 17:09 UTC
Labels: bug
