### ISSUE TITLE
Cannot decimate DataFrame containing timestamps

### ISSUE THREAD

**Issue by amarandon** [pyviz/holoviews#3604] opened 2019-04-03 22:11 UTC
Holoviews looks very interesting, but while trying to use it to plot a time series of oceanographic data, I've run into an issue. I've figured out that my problem has to do with the `decimate` function and its datetime handling. I'm not sure if I'm using it wrong or if there might be a bug. I've made up this minimal example that highlights the issue:

```python
import holoviews as hv
import pandas as pd
from datetime import datetime
from holoviews.operation import decimate
hv.extension("bokeh")

# Generate a Pandas DataFrame containing a column of datetimes
# and a column of arbitray values.
data = [(datetime(2019, 4, i), i) for i in range(1, 5)]
df = pd.DataFrame(data, columns=["date", "value"])

scatter = hv.Curve(df, "date", "value")
decimate(scatter)
```

I get this error when Jupyter attempts to render the plot:

```pytb
TypeError: Cannot compare type 'Timestamp' with type 'int'
```
Note that the `scatter` object displays fine if I don't call `decimate` on it, but since my actual data contains 500,000 points, it's a bit slow. Is there a way to make `decimate` work with a time series?

**Comment by douglasmacdonald** [comment] 2019-04-29 15:19
I found the same problem.

```import pandas as pd
import numpy as np
import holoviews as hv 
from holoviews.operation import decimate

hv.extension('bokeh')
renderer = hv.renderer('bokeh')

pd.date_range('2018-01-01', periods=2000, freq='H')
decimate(hv.Curve(pd.DataFrame({'t':pd.date_range('2018-01-01', periods=2000, freq='H'), 'v':np.arange(2000)})))


WARNING:param.dynamic_operation: Callable raised "TypeError("Cannot compare type 'Timestamp' with type 'int'",)".
Invoked as dynamic_operation(x_range=None, y_range=None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\IPython\core\formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\dimension.py in _repr_mimebundle_(self, include, exclude)
   1291         combined and returned.
   1292         """
-> 1293         return Store.render(self)
   1294 
   1295 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\options.py in render(cls, obj)
   1360         data, metadata = {}, {}
   1361         for hook in hooks:
-> 1362             ret = hook(obj)
   1363             if ret is None:
   1364                 continue

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in pprint_display(obj)
    275     if not ip.display_formatter.formatters['text/plain'].pprint:
    276         return None
--> 277     return display(obj, raw_output=True)
    278 
    279 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in display(obj, raw_output, **kwargs)
    251     elif isinstance(obj, (HoloMap, DynamicMap)):
    252         with option_state(obj):
--> 253             output = map_display(obj)
    254     elif isinstance(obj, Plot):
    255         output = render(obj)

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in wrapped(element)
    140         try:
    141             max_frames = OutputSettings.options['max_frames']
--> 142             mimebundle = fn(element, max_frames=max_frames)
    143             if mimebundle is None:
    144                 return {}, {}

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in map_display(vmap, max_frames)
    200         return None
    201 
--> 202     return render(vmap)
    203 
    204 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\display_hooks.py in render(obj, **kwargs)
     63         renderer = renderer.instance(fig='png')
     64 
---> 65     return renderer.components(obj, **kwargs)
     66 
     67 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\bokeh\renderer.py in components(self, obj, fmt, comm, **kwargs)
    247         # Bokeh has to handle comms directly in <0.12.15
    248         comm = False if bokeh_version < '0.12.15' else comm
--> 249         return super(BokehRenderer, self).components(obj,fmt, comm, **kwargs)
    250 
    251 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\renderer.py in components(self, obj, fmt, comm, **kwargs)
    319             plot = obj
    320         else:
--> 321             plot, fmt = self._validate(obj, fmt)
    322 
    323         widget_id = None

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\renderer.py in _validate(self, obj, fmt, **kwargs)
    218         if isinstance(obj, tuple(self.widgets.values())):
    219             return obj, 'html'
--> 220         plot = self.get_plot(obj, renderer=self, **kwargs)
    221 
    222         fig_formats = self.mode_formats['fig'][self.mode]

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\bokeh\renderer.py in get_plot(self_or_cls, obj, doc, renderer, **kwargs)
    132             curdoc().theme = self_or_cls.theme
    133         doc.theme = self_or_cls.theme
--> 134         plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer, **kwargs)
    135         plot.document = doc
    136         return plot

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\renderer.py in get_plot(self_or_cls, obj, renderer, **kwargs)
    184 
    185         # Initialize DynamicMaps with first data item
--> 186         initialize_dynamic(obj)
    187 
    188         if not isinstance(obj, Plot):

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\plotting\util.py in initialize_dynamic(obj)
    248             continue
    249         if not len(dmap):
--> 250             dmap[dmap._initial_key()]
    251 
    252 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\spaces.py in __getitem__(self, key)
   1322         # Not a cross product and nothing cached so compute element.
   1323         if cache is not None: return cache
-> 1324         val = self._execute_callback(*tuple_key)
   1325         if data_slice:
   1326             val = self._dataslice(val, data_slice)

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\spaces.py in _execute_callback(self, *args)
   1095 
   1096         with dynamicmap_memoization(self.callback, self.streams):
-> 1097             retval = self.callback(*args, **kwargs)
   1098         return self._style(retval)
   1099 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\spaces.py in __call__(self, *args, **kwargs)
    731 
    732         try:
--> 733             ret = self.callable(*args, **kwargs)
    734         except KeyError:
    735             # KeyError is caught separately because it is used to signal

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\util\__init__.py in dynamic_operation(*key, **kwargs)
    921                 kwargs = dict(self._eval_kwargs(), **kwargs)
    922                 obj = map_obj[key] if isinstance(map_obj, HoloMap) else map_obj
--> 923                 return self._process(obj, key, kwargs)
    924         else:
    925             def dynamic_operation(*key, **kwargs):

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\util\__init__.py in _process(self, element, key, kwargs)
    899             kwargs = {k: v for k, v in kwargs.items()
    900                       if k in self.p.operation.params()}
--> 901             return self.p.operation.process_element(element, key, **kwargs)
    902         else:
    903             return self.p.operation(element, **kwargs)

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\operation.py in process_element(self, element, key, **params)
    141         """
    142         self.p = param.ParamOverrides(self, params)
--> 143         return self._apply(element, key)
    144 
    145 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\operation.py in _apply(self, element, key)
    119         for hook in self._preprocess_hooks:
    120             kwargs.update(hook(self, element))
--> 121         ret = self._process(element, key)
    122         for hook in self._postprocess_hooks:
    123             ret = hook(self, ret, **kwargs)

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\operation\element.py in _process(self, element, key)
    701 
    702     def _process(self, element, key=None):
--> 703         return element.map(self._process_layer, Element)
    704 
    705 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\dimension.py in map(self, map_fn, specs, clone)
    701             return deep_mapped
    702         else:
--> 703             return map_fn(self) if applies else self
    704 
    705 

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\operation\element.py in _process_layer(self, element, key)
    693         xdim, ydim = element.dimensions(label=True)[0:2]
    694         sliced = element.select(**{xdim: (xstart, xend),
--> 695                                    ydim: (ystart, yend)})
    696 
    697         if len(sliced) > self.p.max_samples:

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\data\__init__.py in select(self, selection_specs, **selection)
    382             return self
    383 
--> 384         data = self.interface.select(self, **selection)
    385 
    386         if np.isscalar(data):

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\data\pandas.py in select(cls, dataset, selection_mask, **selection)
    266         df = dataset.data
    267         if selection_mask is None:
--> 268             selection_mask = cls.select_mask(dataset, selection)
    269         indexed = cls.indexed(dataset, selection)
    270         df = df.iloc[selection_mask]

C:\ProgramData\Anaconda3\envs\holoviews\lib\site-packages\holoviews\core\data\interface.py in select_mask(cls, dataset, selection)
    292                     warnings.filterwarnings('ignore', r'invalid value encountered')
    293                     if k.start is not None:
--> 294                         mask &= k.start <= arr
    295                     if k.stop is not None:
    296                         mask &= arr < k.stop

pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps._Timestamp.__richcmp__()

pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps._Timestamp.__richcmp__()

TypeError: Cannot compare type 'Timestamp' with type 'int```

**Comment by darynwhite** [comment] 2019-06-21 00:08
I am running into the same problem as well, also while building an overlay of Curve objects that are on the same DateTime index. 

Looking at the error report on my system, which is the same as @douglasmacdonald here:
>` --> 695                                    ydim: (ystart, yend)})`

Appears to be the offending line, though I'm unable to determine the cause. Could this have something to do with it not normalizing the dates into integers before slicing?

As I expect to be frequently having plots with 600k+ datapoints, decimate would be invaluable. Datashader might be an option, but from my tests, it doesn't give the same level of detail that the raw Bokeh plots provide. Any input would be welcome!

**Comment by poplarShift** [comment] 2019-06-21 00:36
@darynwhite Looks like it's simply datetime axis slicing that's missing here. There's a semi-dormant PR here: https://github.com/pyviz/holoviews/pull/3197 that could use a round of review  since I've been tinkering around with it so if you get @philippjfr to have a look that may speed things up :)

**Comment by darynwhite** [comment] 2019-06-21 16:17
@poplarShift Thanks for commenting about this, following your PR reference and looking over the comments from the referenced issues, especially #3697, really revealed why I've been struggling with pandas DataFrames that have a DateTime index. I'll try and pull down that branch and test it, if it seems to solve the problems I've run into, I'll try and get that PR merged into the next release.

**Comment by darynwhite** [comment] 2019-06-25 01:02
That branch proved capable of decimating at least some of the data I handed it.

Here's a quick screen capture of an Air Temp dataset:
![Screen Recording 2019-06-24 at 17 29 03](https://user-images.githubusercontent.com/40304663/60061438-09879d00-96aa-11e9-9d38-31b6ea085d88.gif)

But it isn't quite there yet, perhaps conversion away from the OrderedDict structure will prove to be effective.

**Comment by philippjfr** [comment] 2019-09-23 09:39
Seems to have been fixed.

**Closed by philippjfr** 2019-09-23 09:39 UTC
