### ISSUE TITLE
HoloMaps gets confused about options

### ISSUE THREAD

**Issue by ea42gh** [pyviz/holoviews#1800] opened 2017-08-09 18:18 UTC
```
%%output backend='matplotlib'  size=150
%%opts Spikes Scatter {+framewise}
opt1=dict(s=50, color='darkgreen')
opt0=dict(s=50, color='indianred')

SZ=8000; N=44; M=4
ddf  = pd.DataFrame( dict(err      = 5+np.random.normal(size=SZ),
                          Accept   = np.random.randint(2,size=SZ),
                          resultID = np.random.randint(N,size=SZ),
                          probID   = np.arange(SZ)
    ))
ddf.ix[ddf['resultID']==0,'Accept'] = 0

dd_plots={}
for n in np.arange(N):
    hv_df = hv.Table(ddf[ddf['resultID']==n], kdims=['probID'], vdims=['err','Accept', 'resultID'])
    if len(hv_df) is 0: continue

    h = hv.Spikes( hv_df, kdims=['probID'], vdims=['err']).opts(plot=dict(xticks=5, yticks=5, fig_size=600, aspect=5))

    tmp1 = hv_df[hv_df['Accept']==1]
    if len(tmp1) > 0: h = h * hv.Scatter( tmp1, kdims=['probID'], vdims=['err'] ).opts(style=opt1 )
    tmp0 = hv_df[hv_df['Accept']==0]
    if len(tmp0) > 0: h = h * hv.Scatter( tmp0, kdims=['probID'], vdims=['err'] ).opts(style=opt0 )

    dd_plots[n] = h.relabel('Error Evolution resultID = %d' % n)

(hv.HoloMap(dd_plots)+dd_plots[0]).cols(1)
```
results in a HoloMap that has the coloration of dd_plots[0] wrong.

Real data has resulted in behavior such that all options are replaced with either opt0 or opt1.
In one instance I observed one of the ScatterPlots not being displayed at all.

A fix is to always add a Scatter().opts() element even if there is no data
(i.e., I added artificial data and reset the ranges so it would not be displayed...)

**Comment by philippjfr** [comment] 2017-09-04 13:42
Okay after investigating this, there are two seeming bugs here:

1) In matplotlib the first frame of the upper plot is incorrectly colored 'darkgreen' when it should be 'indianred'
2) In bokeh all frames after the first one are missing the 'indianred' scatter points.

**Comment by ea42gh** [comment] 2017-09-04 21:31
Actually, there is other pathological behavior that I have observed but can't readily duplicate:
e.g., some of the Scatter markers have gone missing altogether (bokeh)

**Comment by philippjfr** [comment] 2017-09-04 22:13
That's what I was trying to say with 2., I can reproduce, so I'll look into it.

**Comment by philippjfr** [comment] 2017-10-28 19:11
I'm not going to get to this before release, but the behavior at least seems to have improved, both for matplotlib and bokeh.

**Comment by jlstevens** [comment] 2017-10-28 19:21
It would be good to know which parts are actually fixed and which bits are still broken. If the behavior improved enough it would be fixed and we could close the issue...

**Comment by philippjfr** [comment] 2019-02-09 14:08
Most issues here seem to have been fixed but the issue is not very specific so it's hard to tell if that covers all of them. If there are remaining bugs here they should be filed as separate issues with very specific descriptions of what is actually going wrong.

**Closed by philippjfr** 2019-02-09 14:08 UTC
Labels: bug
