### ISSUE TITLE
Barbs element

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoviews#3901] opened 2019-08-14 19:29 UTC
Barbs would probably mirror VectorField for matplotlib backend, but not sure how to do it with bokeh. Maybe this would only be for matplotlib similar to Scatter3D is limited to only matplotlib/plotly.

https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.barbs.html

**Comment by philippjfr** [comment] 2019-08-14 19:32
Duplicate of https://github.com/pyviz/geoviews/issues/133

**Closed by philippjfr** 2019-08-14 19:32 UTC

**Comment by ahuang11** [comment] 2019-08-14 19:36
Ah, I knew I saw it somewhere, but didn't know where. Should the issue be filed in geoviews? I feel like barbs doesn't necessarily have to be plotted on a map e.g. the right y-axis of a Skew-T https://unidata.github.io/MetPy/latest/examples/plots/Skew-T_Layout.html

**Comment by philippjfr** [comment] 2019-08-14 19:39
That's true, it's not necessarily in a geographic coordinates but I still feel like it's so specialized that GeoViews is the appropriate place for it.

**Comment by jbednar** [comment] 2019-08-14 20:23
I agree; should be in GeoViews.  It would confuse people and be distracting if it were in HoloViews.
