### ISSUE TITLE
Add topics notebooks to the gallery

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#1638] opened 2017-06-28 15:47 UTC
We briefly added a 'Showcase' page to the new holoviews website but decided that page wasn't worth another top level heading. Instead, we are going to hide that heading/page for now with the plan to add topics to the gallery (with custom thumbnails as necessary) to show the content that we had planned for showcase.

We aren't 100% on this plan just yet (other than hiding showcase for now) as we need to be sure everything we want can be framed in this way.

**Comment by jlstevens** [comment] 2017-06-30 10:41
I'll work on cleaning up my logistic map and reaction diffusion notebooks. I know they work so it won't take long.

**Comment by jbednar** [comment] 2018-05-04 14:49
The topics examples should probably go to pyviz.org instead; I think they'll illustrate how to use PyViz tools to explore topics, rather than specifically how to use HoloViews.

**Comment by jlstevens** [comment] 2018-05-04 15:31
Agreed. And the same thing has been decided for the datashader topics too?

**Comment by jbednar** [comment] 2018-05-04 15:32
Yes.

**Comment by philippjfr** [comment] 2019-10-02 23:59
The notebooks now live on example.pyviz.org but we should still link to them.

**Comment by philippjfr** [comment] 2019-10-08 09:04
Duplicate of #4037 now.

**Closed by philippjfr** 2019-10-08 09:04 UTC
Labels: docs
