### ISSUE TITLE
Colobar affects equal aspect ratio of Image

### ISSUE THREAD

**Issue by jakirkham** [pyviz/holoviews#2177] opened 2017-12-06 00:45 UTC
Recently was playing around with Holoviews' `Image` object and noticed that when setting `aspect="equal"` adding or removing the colorbar seemed to affect how the image was displayed. It seems like the colorbar might be factored into the aspect ratio calculation. Though there might be a little more going on. Here's an example [notebook]( http://nbviewer.jupyter.org/gist/jakirkham/6c329321784f7bf2fbf08cc54de08271 ) demonstrating this behavior. Environment details below.

<details>
<summary>Environment:</summary>

```yaml
name: test
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- blas=1.1=openblas
- bleach=2.0.0=py36_0
- bokeh=0.12.11=py36_0
- ca-certificates=2017.11.5=0
- certifi=2017.11.5=py36_0
- cycler=0.10.0=py36_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_1
- freetype=2.7=1
- holoviews=1.9.1=py36_0
- html5lib=0.999999999=py36_0
- icu=58.2=0
- ipykernel=4.6.1=py36_0
- ipython=6.2.1=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.0.5=py36_0
- jedi=0.10.2=py36_0
- jinja2=2.10=py36_0
- jpeg=9b=2
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.4.0=py_0
- lancet=0.9.0=py36_0
- libgfortran=3.0.0=0
- libpng=1.6.34=0
- libsodium=1.0.15=1
- markupsafe=1.0=py36_0
- matplotlib=2.1.0=py36_0
- mistune=0.8=py36_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- notebook=5.2.2=py36_1
- numpy=1.13.3=py36_blas_openblas_201
- openblas=0.2.20=6
- openssl=1.0.2m=0
- pandoc=2.0.4=0
- pandocfilters=1.4.1=py36_0
- param=1.5.1=py36_0
- pexpect=4.3.0=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- python=3.6.3=1
- python-dateutil=2.6.1=py36_0
- pytz=2017.3=py_2
- pyyaml=3.12=py36_1
- pyzmq=16.0.2=py36_2
- qt=5.6.2=h9e3eb04_4
- qtconsole=4.3.1=py36_0
- readline=6.2=0
- setuptools=38.2.3=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlite=3.13.0=1
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.19=2
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.30.0=py_1
- widgetsnbextension=3.0.8=py36_0
- xz=5.2.3=0
- yaml=0.1.7=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
```

</details>

**Comment by jakirkham** [comment] 2017-12-06 00:46
If there are any ideas on workarounds, would be open to trying a few.

**Comment by ceball** [comment] 2017-12-06 01:00
(Happens with bokeh, but not matplotlib: see #1947.)

**Comment by jakirkham** [comment] 2017-12-06 01:12
Ah ok. Thanks. Would prefer to use Bokeh if possible.

Also sorry if I duped. Searched the issue tracker, but somehow missed that one. So wrote this up. Feel free to close if you think discussion is better dealt with in the other issue.

**Comment by jakirkham** [comment] 2017-12-06 05:01
Just as a note for myself and maybe other happening across this, this is caused by Bokeh issue ( https://github.com/bokeh/bokeh/issues/5186 ).

**Comment by philippjfr** [comment] 2019-02-09 14:40
Indeed a duplicate of https://github.com/pyviz/holoviews/issues/1947, closing.

**Closed by philippjfr** 2019-02-09 14:40 UTC
